services:
  onemile_db:
    image: postgres:latest
    container_name: onemile_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PRODDB_NAME}
      POSTGRES_USER: ${PRODDB_USER}
      POSTGRES_PASSWORD: ${PRODDB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
        - onemile_data:/var/lib/postgresql/data

  onemile_app:
    build: .
    container_name: onemile_app
    restart: unless-stopped
    depends_on:
      - onemile_db
    ports:
      - "8000:8000"
    environment:
      CORESETTINGS_DATABASES: '{"default":{"HOST": "onemile_db"}}'
      CORESETTINGS_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

volumes:
  onemile_data:
    driver: local
